apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  namespace: gx-lab
  labels:
    io.kompose.service: data
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
